# ---------- BUILD STAGE ----------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore
COPY logger.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# ---------- RUNTIME STAGE ----------
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

# Copy build output
COPY --from=build /app/out .

# Render provides PORT env variable
ENV ASPNETCORE_URLS=http://+:${PORT}

# IMPORTANT: dll name must match project name
ENTRYPOINT ["dotnet", "logger.dll"]
